name: build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.1

      - name: get build_id from build.txt
        id: get_build
        run: |
          BUILD=$(cat build.txt | tr -d ' \n')
          echo "build_id=$BUILD" >> $GITHUB_OUTPUT

      - name: check if release already exists
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get_build.outputs.build_id }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG already exists. Skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: build image
        run: |
          IMAGE=${{ github.repository }}
          ls -la
          docker build -f dockerfile -t $IMAGE:local .

      - name: extract game version
        if: steps.check_release.outputs.exists == 'false'
        id: get_version
        run: |
          IMAGE="${{ github.repository }}:local"
          VERSION=$(docker run --rm $IMAGE cat /home/steam/dst/game/version.txt | tr -d ' \n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: log in to container registry [github]
        if: steps.check_release.outputs.exists == 'false'
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: log in to container registry [docker]
        if: steps.check_release.outputs.exists == 'false'
        uses: docker/login-action@v3.6.0
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: tag image
        if: steps.check_release.outputs.exists == 'false'
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker tag ghcr.io/${{ github.repository }}:${{ steps.get_build.outputs.build_id }}
          docker tag ghcr.io/${{ github.repository }}:latest
          docker tag docker.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker tag docker.io/${{ github.repository }}:${{ steps.get_build.outputs.build_id }}
          docker tag docker.io/${{ github.repository }}:latest

      - name: push image
        if: steps.check_release.outputs.exists == 'false'
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/${{ github.repository }}:${{ steps.get_build.outputs.build_id }}
          docker push ghcr.io/${{ github.repository }}:latest
          docker push docker.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}
          docker push docker.io/${{ github.repository }}:${{ steps.get_build.outputs.build_id }}
          docker push docker.io/${{ github.repository }}:latest

      - name: create github release
        if: steps.check_release.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD: ${{ steps.get_build.outputs.build_id }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          gh release create "$BUILD" \
            --title "v$VERSION" \
            --notes "Build ID: $BUILD | Internal Game Version: $VERSION"
